### PR TITLE
Comment out copyright notice

### PR DESCRIPTION
**Pull request by metalefty**
Changes proposed in this pull request:
 - 
 - 
 - 

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- Option 1

### CODE REVIEW

**Comment by metalefty** [comment]
@dnobori not only `src/Mayaqua/Network.c`, in lots of files, the following lines are not commented out and fails to compile.

```
Copyright (c) all contributors on SoftEther VPN project in GitHub.
```

**Comment by dnobori** [comment]
Thank you. I am going to fix them.

**Comment by metalefty** [comment]
Just FYI, I got file list that needs to be fixed in this way:
```
(zsh)% git grep ^Copyright **/*.{c,h,cs} | cut -d: -f1
```

**Comment by metalefty** [comment]
Quick hack to compile.
```sh
tar zxf softether-src-v4.29-9678-rtm.tar.gz
cd v4.29-9678
find . \( -name \*.c -o -name \*.h -o -name \*.cs \) -print0 | xargs -0 sed -i .bak -e 's|^\(Copyright (c) all contributors on SoftEther VPN project in GitHub.\)|// \1|'
```

**Comment by metalefty** [comment]
Fixed all and force pushed. Feel free either to merge or fix by your own and discard my PR.

**Comment by dnobori** [comment]
I believe I fixed everything. Thank you so much.

**Comment by metalefty** [comment]
v4.29-9680 looks fine, thanks!

**Pull request closed without merging**
